evrardjp/ansible-keepalived

README.md, defaults/main.yml, tasks/main.yml
This introduces the use of a ppa for installing keepalived by default.
This behaviour can be reversed by adapting the variable "keepalived_use_latest_stable_ppa"
=> Use more recent keepalived with a ubuntu ppa

README.md, UPGRADE.md, defaults/main.yml, tasks/keepalived_install_apt.yml, tasks/main.yml, vars/ubuntu-14.04.yml
Multi-OS support was included in previous commit, but variable names
didn't make sense anymore.
This should fix this.
Signed-off-by: Jean-Philippe Evrard <jean-philippe@evrard.me>
=> Rewrite the multi-os support

README.md
Both keepalived_servers and keepalived_hosts was being used. This
commit fixes both examples to use keepalived_hosts to aid clarity.
=> fix example usage in README.md

defaults/main.yml, tasks/keepalived_install_apt.yml, vars/ubuntu-14.04.yml, vars/ubuntu-16.04.yml
Instead of using a ppa, some deployers may want to use ubuntu cloud
archive to install keepalived.
This commit introduces two variables to change the default behavior (of
installing with ppa): keepalived_uca_enable and uca_apt_repo_url
The first variable is defaulted to false, and if set to true, keepalived
will be installed with ubuntu cloud archive.
The second variable is the url to the uca repository, which can be
overriden if you want to define your own mirror of the uca repository
(Defaults to: "http://ubuntu-cloud.archive.canonical.com/ubuntu")
Signed-off-by: Jean-Philippe Evrard <jean-philippe@evrard.me>
=> Introduced Ubuntu Cloud Archive installation method

tasks/keepalived_install_apt.yml
Ansible 2.2 is now less indulgent to typos compared to previous versions.
The conditional in the apt update task was incorrect and "False" or False
returned True.
This fixes it.
As a summary, ansible now behave correctly. Woot! 
(Please insert rainbows and unicorns)
Signed-off-by: Jean-Philippe Evrard <jean-philippe@evrard.me>
=> Fix typo in update apt condititional

tasks/keepalived_install_apt.yml
Update role to pass latest ansible-lint tests.
Tying the UCA apt key status to the keepalived package state is a fair change because we do not need to enforce the UCA key state if we are not forcing updates on keepalived.
=> Fix linting issues for ansible-lint 3.4.1

tasks/keepalived_install_apt.yml
Now ansible apt module correctly behaves, so it's time
to deprecate these cruft tasks for apt.
=> Remove ansible<2.2 apt cache hack

meta/main.yml, tasks/keepalived_install_yum.yml, tasks/main.yml
This patch adds CentOS 7 support for the keepalived role.
=> Add CentOS 7 support

README.md, templates/keepalived.conf.j2, vars/keepalived_haproxy_backup_example.yml, vars/keepalived_haproxy_master_example.yml
Hello @evrardjp,
this PR enables the user to define virtual_servers with this role. We plan to use it in our new internal DNS infrastructure.
Please let me know if something can be done better.
I mostly used [the officlal git repo](https://github.com/acassen/keepalived/blob/v1.2.23/doc/keepalived.conf.SYNOPSIS) to determine the required syntax. If you like I can also add a link to the official repo in the README.md.
Thank you and best regards
Jard
=> added optional virtual_server config

files/keepalived_ping.te, tasks/keepalived_selinux.yml, tasks/main.yml
The `ping` command used by keepalived causes SELinux AVC denials on
CentOS 7. This causes keepalived to think that all of the systems
are unstable and it can't find a suitable host to run services.
This patch adds a policy that allows keepalived to function without
causing AVCs.
For more details:
https://bugs.launchpad.net/openstack-ansible/+bug/1660426
=> Add SELinux module for keepalived's ping cmd

vars/ubuntu-16.04.yml
Latest ppa changed the name of service from ``keepalived`` to
``keepalived.service``.. It should be safe to use
``keepalived.service`` for all the systemd versions, therefore
we are moving to it.
=> Fix latest service name

tasks/keepalived_install_yum.yml
https://rpmfind.net/linux/RPM/centos/7.3.1611/x86_64/Packages/keepalived-1.2.13-8.el7.x86_64.html
=> keepalived do not need epel.

templates/keepalived.conf.j2
Passing the check script configuration as strings will
cause keepalived, at least version 1.2.19, to parse them
as boolean causing race conditions like check scripts
always failing when the response take longer than one second
and faulting the keepalived states.
=> Fix parsing issues for the rise, fall and interval configuration

templates/keepalived.conf.j2
Extended template to support virtual routes for VRRP, adding routes if becoming master, deleting them for backup.
=> Support for virtual routes for VRRP instances

templates/keepalived.conf.j2
Hello @evrardjp,
here comes a small fix on the warmup setting on the misc_check's.
According to the official [documentation](https://github.com/acassen/keepalived/blob/master/doc/keepalived.conf.SYNOPSIS#L688) a integer value needs to be provided after the keyword.
Best
Jard
=> set missing value after warmup key

tasks/keepalived_install.yml
Ansible lint issue ANSIBLE 0010 is appearing here, requiring the
package state to be present. If a deployer deploys with UCA,
it makes sense to always have the latest version of the UCA
keyring, when making sure it will install the latest version of
the package.
=> Fix ansible lint issue

defaults/main.yml, files/keepalived_haproxy_pid_file.te, tasks/keepalived_selinux.yml, tasks/keepalived_selinux_compile.yml
On CentOS 7, an SELinux denial occurs when keepalived tries to read
haproxy's PID file. This patch adds SELinux policy to allow this
activity and breaks the SELinux compilation part of the role into
a reusable set of tasks.
=> SELinux: allow keepalived to cat haproxy pid

templates/keepalived.conf.j2
iteritems is a py2 callable and will break when using py3.
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
=> remove the use of iteritems

defaults/main.yml, files/keepalived_setpgid.te
When keepalived tries to set the progress group with the setpgid()
call, the access is denied by SELinux. This patch allows keepalived
to make the syscall.
Closes-Bug: https://bugs.launchpad.net/openstack-ansible/+bug/1732521
=> Fix SELinux AVC when using setpgid

tests/deploy.yml
The ansible_play_host is not ordered the same way at every run.
If the first node happen to be keepalived2 instead of 1 or 3, the
VRRP convergence test would fail, as the test was looking into
the presence of the VRRP master ip on the eth1 NIC, which is not
the NIC name for ubuntu 16.04.
This moves to use {{ vrrp_nic }} instead of hardcoding eth1, and
ensures as much as possible a deterministic order for ansible 2.4
runs.
On top of that, a vagrant provision done twice would report
the provisioning as "changed" instead of "ok", only because we
are using a raw task for installing python2 on the ubuntu 16.04
node, which is considered as the minimum to run ansible.
This task to install python2 shouldn't be
considered as a change of ansible-keepalived itself, and shouldn't
impact idempotency …
=> Improve robustness of Vagrant tests

Vagrantfile, handlers/main.yml, tasks/keepalived_install.yml, tests/deploy.yml, tests/group_vars/all.yml, tests/host_vars/keepalived2.yml, tests/host_vars/keepalived3.yml, vars/ubuntu-16.04.yml
the PR #53 has demonstrated an issue of coverage: The Vagrant test was only caring about ppa, and not uca, which should be technically the same.
However, the ppa now ships with different files (systemd units/sample files) causing discrependencies with different deploy methods.
This PR adds testing and adds, at the same time, the needed work of PR #53 .
=> Update of PR53 with extra coverage

tasks/main.yml
This patch adds a systemd override that makes keepalived start once
all networking interfaces are fully online.
=> Ensure keepalived starts after networking

defaults/main.yml, templates/keepalived.conf.j2
When `enable_script_security` is not present in keepalived.conf,
the daemon will print a warning in the journal:
SECURITY VIOLATION - scripts are being executed but
script_security not enabled.
This patch enables script security which ensures that a non-root
user cannot maliciously alter a script that keepalived may be running
as root.
This fixes Launchpad bug 1742487:
https://bugs.launchpad.net/openstack-ansible/+bug/1742487
=> Add keepalived_global_defs configuration directive

defaults/main.yml
keepalived_instances is supposed to be a dict, but the default
value is a list.
Thanks to @rlex for the bug.
=> Fix keepalived_instances default data type

Vagrantfile, tests/deploy.yml, tests/functional-test.yml, vars/debian.yml
Requested by @rlex.
A few remarks:
- python-apt isn't present in the vagrant image, so we install it
- this has caught an issue with the testing: some images don't
have ifconfig anymore
- this also adds functional testing of more nodes now, not
only the last one.
=> Add Debian Stretch support

tasks/keepalived_install.yml
If an apt task is used with check mode and python-apt isn't
installed, the task will fail. Technically the package python-apt
is installed during module execution when not running check-mode,
so it makes sense to add it before running check mode to avoid
implicit dependencies.
=> Do not imply python-apt is installed

defaults/main.yml, tasks/main.yml, vars/debian.yml, vars/redhat.yml, vars/suse.yml, vars/ubuntu-14.04.yml, vars/ubuntu-16.04.yml
It may be used for providing extra args for keepalived daemon.
With these args it's possible to change logging options or enabling SNMP checks.
=> Added ability to specify daemon launch arguments.

meta/main.yml, tasks/keepalived_install.yml, tasks/keepalived_selinux.yml
Hello! This PR:
1) Will fix "Using tests as filters is deprecated"
2) Will fix "Invoking "yum" only once while using a loop via squash_actions is deprecated"
All changes are internal, so there is no functional/syntax changes.
=> Deprecation fixes

templates/keepalived.conf.j2
Make it possible to use `TCP_CHECK`s in the keepalived configuration.
=> Extend realservers check configuration

tasks/main.yml
If we just use "check_script" and "src_check_script",
the file from the source will be copy, to the target,
and take the name set on "check_script". This could be
an issue if we have parameters under "check_script".
For example, if we have something like:
check_script: "/etc/keepalived/pingable_check.sh
{{ keepalived_ping_count }} {{ keepalived_ping_address }}"
We could end up with a file name:
"/etc/keepalived/pingable_check.sh 1 203.0.113.89"
We should for that have an optional field for setting
the destination without taking the parameters,
like dest_check_script.
=> Add ability to have src_check_script and check_script with parameters

templates/keepalived.conf.j2, tests/keepalived_haproxy_master_example.yml
Add the SSL_GET section for real_servers, as described in
https://manpages.debian.org/stretch/keepalived/keepalived.conf.5.en.html
Search for "SSL_GET"
=> Add ssl_get check

LICENSE, defaults/main.yml, templates/keepalived.conf.j2, tests/keepalived_haproxy_master_example.yml
I use gilt[1] to pull in my Ansible roles, and a series of
pre-commit hooks which correct trailing whitespace and
newlines.  These are triggered when I vendor your project
into my repo.  Since this doesn't look too controversial,
figured I'd submit a PR.
[1]: https://gilt.readthedocs.io/en/latest/
=> Pre-commit fixups

defaults/main.yml, tasks/main.yml
Some operating systems may have proper settings already - i.e. CentOS 7+
=> Allow not to create overrides for keepalived.service (systemd)

tasks/keepalived_selinux.yml, tasks/keepalived_selinux_compile.yml, tasks/main.yml
Currently in check mode (--check) role fails with error:
> The conditional check 'selinux_policy_name not in selinux_modules.stdout' failed. The error was: error while evaluating conditional (selinux_policy_name not in selinux_modules.stdout): Unable to look up a name or access an attribute in template string ({% if selinux_policy_name not in selinux_modules.stdout %} True {% else %} False {% endif %}).
> Make sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable
These commits prevent such error and installing SELinux-related packages when list `keepalived_selinux_compile_rules` is empty.
=> SELinux fixes (check mode)

templates/keepalived.conf.j2
While the template itself is copyright-protected, I would not consider the generated config file a Derivative Work, therefore (as far as I know) it should not contain the Apache license template.
=> Do not pass the copyright notice to the generated file

templates/keepalived.conf.j2, tests/keepalived_haproxy_master_example.yml
Hello again,
some smaller additions. 
- vrrp advert_int 
- real_server weight
- real_server uthreshold
- real_server lthreshold
another pull request will follow, because I would like to add `virtual_server_group` 
> This feature offers a way to simplify your configuration by factorizing virtual server
> definitions. If you need to define a bunch of virtual servers with exactly the same
> real server topology then this feature will make your configuration much more readable
> and will optimize healthchecking task by only spawning one healthchecking where
> multiple virtual server declaration will spawn a dedicated healthchecker for every
> real server which will waste system resources.
that would include a split up of the current `keepalived.conf.j2` template to reduce duplicate code …
=> add advert_int, weight and thresholds

templates/keepalived.conf.j2, tests/keepalived_haproxy_master_example.yml
Keepalived has a feature to include IP addresses that keepalived
should bring up and down, but not include in VRRP packets.
=> Add optional virtual_ipaddress_excluded section

tasks/main.yml
In cases when keepalived is currently masked, service
enable will not work. So service will
stay in masked state and won't start with handler either.
=> Ensure that keepalived is not masked

tasks/keepalived_install.yml
In case keepalived_package_state is latest it is important to restart
service in case package has been upgraded
This also adds handlers flush once role is finished.
=> Restart keepalived on package change

handlers/main.yml, tasks/main.yml
Systemd unit files are modified and the daemon needs to be reloaded so that it can pick them up. In order for this to be restarted before the keepalived service, this needs to be the first task in the handlers file.
Current issue with the role will give you the following warning as the unit files have not been refreshed.
```
$ systemctl status keepalived
Warning: The unit file, source configuration file or drop-ins of keepalived.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```
=> fix systemtcl unit file refresh

handlers/main.yml, tasks/keepalived_install.yml, tasks/main.yml
Without this, molecule testing and some other environments are
broken and can't install keepalived.
This should fix it until the fix above is backported to stable
Ansible branches.
=> Workaround https://github.com/ansible/ansible/pull/72337

templates/keepalived.conf.j2, tests/keepalived_haproxy_master_example.yml
I needed to configure keepalived to use a virtual MAC address. I've added it as a boolean option.
The molecule tests seem to pass. I have tested the against a couple of hosts and it worked. Please let me know if anything else is required for this to be approved. Thanks!
=> feat: Add support for virtual MAC address

tasks/main.yml, templates/keepalived.conf.j2, tests/keepalived_haproxy_backup_example.yml, tests/keepalived_haproxy_master_example.yml
Description taken from (https://xiaoz.co/2020/09/30/keepalived-and-gratuitous-arp/)
```
If a lower priority router has transitioned to master, there has presumably
been an intermittent communications break between the master and backup. It
appears that servers in an Amazon AWS environment can experience this.
The problem then occurs if a notify_master script is executed on the backup
that has just transitioned to master and the script executes something like
a `aws ec2 assign-private-ip-addresses` command, thereby removing the address
from the 'proper' master. Executing notify_master_rx_lower_pri notification
allows the 'proper' master to recover the secondary addresses.
```
I had some race conditions when calling a SOAP Service Endpoint to switch the FloatingIP to the masters. With this …
=> Add config option "notify_master_rx_lower_pri"

defaults/main.yml, tasks/main.yml
In case of VIP failover some connections (like mysql) can stuck
in retrying to connect and detect a dead connection. We
should probably make this failover to be detected faster then the
default value as suggested in [1]
[1] https://access.redhat.com/solutions/726753
Related-Bug: https://bugs.launchpad.net/kolla-ansible/+bug/1917068
=> Decrease TCP retries in case of VIP failover

templates/keepalived.conf.j2
There is no such thing as notify_master_rx_lower_pri for
sync_groups.
This should fix it incorrect templates.
Closes: #170
=> Remove notify_master_rx_lower_pri from sync_group

tasks/main.yml, tests/keepalived_haproxy_backup_example.yml, tests/keepalived_haproxy_master_example.yml
The previous patch removed the incorrect templating, but didn't
remove the scripts and the examples in the documentation.
This should fix it.
Closes: #170
=> fix: Remove incorrect sync_group notify_master_rx_lower_pri

molecule/default/cleanup.yml, molecule/default/converge.yml, molecule/default/prepare.yml, tox.ini
Without this patch, the ansible 2.9 tests can effectively install
2.10.0.
This is a problem, as it's not covering the right ansible versions.
This should fix it.
=> Fix Ansible 2.9 tests

.ansible-lint, molecule/default/molecule.yml
A new ansible lint requires removal of blank lines.
I am not against that rule, so I will keep it applied, and fix
my failing ansible-lint instead.
=> Remove blank lines for linting

defaults/main.yml, tasks/main.yml
Hi,
Commands like "killall -0" are frequently used with keepalived. This PR aims to ease the installation of the packages providing those commands.
=> install dependencies required by keepalived scripts

templates/keepalived-checks.j2
needed some http options. ended adding all missing checks and check options
=> Add missing check options and missing checks

templates/keepalived.conf.j2
Add support for the vmac_xmit_base option of keepalived (https://github.com/acassen/keepalived/blob/master/doc/NOTE_vrrp_vmac.txt)
=> add vmac_xmit_base support

.github/workflows/molecule.yml, meta/main.yml, molecule/default/molecule.yml, tox-requirements.txt, tox.ini
This makes it hard to manage, from molecule perspective:
We would need to pin to molecule-docker below 1.0.
Let's just move on with 2.10. It's time now.
Closes: #190
=> Remove 2.9 support

tasks/keepalived_selinux.yml, tasks/main.yml
fixes:
`[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in version 2.16.`
=> fix usage of deprecated include

.ansible-lint
added fqcn-builtins to ansible-lint skip_list
=> FIX "fqcn-builtins Use FQCN for builtin actions." on ansible lint run

defaults/main.yml, templates/keepalived.conf.j2
Output is by default enabled but can be disabled
using variable keepalived_show_ansible_managed set to false.
=> Add ansible_managed output to keepalived.conf

templates/keepalived.conf.j2
In case if user needs to change the `auth_type` variable value to `AH`.
=> Make "auth_type" variable optional with default value

dev-requirements.txt, tox.ini
dependabot only understand {dev-,test-,}requirements.txt.
We need to rename the tox-requirements into dev-requirements,
so that dependabot can maintain it.
We can then freeze the dependencies in test, and use dependabot
to automatically bump the deps.
This will increase stability for maintainers (no PR will fail due
to test env), while at the same time we will have dependabot to
still show us the issues originated from upstream changes
on a more frequent basis.
=> Make way for using dependabot for requirements

.ansible-lint, templates/keepalived.conf.j2
As discussed in (draft) PR [1], we need to split the new features
and the general code updates. This tackles the feature additions
that are pending for a while.
Closes: #140  #176 #195 
[1]: https://github.com/evrardjp/ansible-keepalived/pull/203
=> Add new features vrrp_track_file, track_files, (no) accept, and safeguards.

meta/main.yml
ansible-lint now needs strings and is now inspecting the schema.
We should do the right thing (TM) by ensuring the data types are
correct.
Side note: The Ansible version is not a numeric type and needs to
be a string to pass validation as of today.
=> Fix meta for ansible-lint

tasks/main.yml, tests/keepalived_haproxy_combined_example.yml
This should ensure the config is working well before attempting
a reboot.
Closes: #172
=> Validate configuration if keepalived >= 2.0.4

templates/keepalived.conf.j2
Without this patch, it's impossible to have keepalived working
without a VIP (for the rare cases without VIPs).
Closes: #167
=> Make vips optional

ansible210-requirements.txt, dev-requirements.txt, molecule/default/converge.yml, tox.ini
The ansible package ansible==2.10 is NOT having the proper
constraint to matching ansible-base/ansible-core. So it means
that pip happily installs ansible==2.10 then installs
ansible-core 2.13. This means the code actually running
in ansible-2.10 testing is ansible-2.13.
This is a problem, as the testing for ansible-2.10 is not
actually testing 2.10.
This fixes it by splitting the two test environments, having two
different requirements files. We do not lock or constrain
(yet!) the dependencies, as this would mean extra effort
in the tooling.
In the meantime, contributors should ensure that the right
version of ansible-core/base is installed.
=> Split ansible-2.10 requirements from dev

tasks/main.yml
I'm not able to run the playbook in check mode due to the "Output keepalived version" task. ansible.builtin.command doesn't run in check mode because it assumes changes are being made. No changes are being made in this case, so I've added 'check_mode: no'.
Docs for the check_mode option are here: https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html#enforcing-or-preventing-check-mode-on-tasks
=> Add support for checkmode in tasks/main.yml

defaults/main.yml, tasks/main.yml
This patch addresses a few issues with recent changes, including:
- The 'validate' template directive fails due to check scripts not yet being dropped
- The scripts not being dropped due to the conditional not being met
- keepalived_scripts being changed to keepalived_sync_groups (inadvertently?)
NOTE: This patch only addresses the tracking scripts, but may need to be modified to address similar issues with other notification scripts.
=> Fixes conditional logic and other issues with dropping scripts

tox.ini
I frequently have to deal with broken CI due to system changes:
- systemd gets updated, and start to break cgroup integration of docker
- docker includes a bug, so molecule tests starts to fail
- molecule gets updated, dependencies are a mess
- molecule[docker] gets updated, same issues.
I am tired of maintaining this fragile CI. I will remove it.
There is no less fragile option that I know of.
Github actions could be used to test basic features, like deployment. It cannot test the clustering, as we do not have an inventory containing multiple nodes.
If anyone is interested by brining the test coverage back, I am fine with it, please submit a PR.
=> Disable CI until a solution for molecule is found

files/keepalived_notifications.sh
Found this role being used in a project I'm collaborating on, where I want to run shellcheck on every single shellscript, so figured I'd patch this one and submit a PR.
=> Commenting out unused variables for shellcheck compliance.

tasks/keepalived_selinux.yml, tasks/keepalived_selinux_compile.yml
Hi,
I like to keep forks of roles to a minimum and often refer to files (like your `keepalived_selinux_compile_rules` list) by absolute paths, usually based on `inventory_dir` or similar. This isn't supported currently as it assumes each item in that list is a filename. This PR adds a new var for the basename which is used in most places. It has no effect on the default values and shouldn't be a breaking change for existing users as I expect it currently fails with relative paths like it does with absolute ones.
I've also changed the check used for installing SELinux packages to check against the first element in `keepalived_selinux_compile_rules` instead of hardcoding `keepalived_ping`, which might be removed by a user overriding the list and thus missing the requirements for compiling …
=> Support absolute paths for SELinux modules

templates/keepalived-virtual-server.j2
We need to set the flag `inhibit_on_failure` in our environment.
=> Support virtualserver/inhibit_on_failure

templates/keepalived.conf.j2
see https://manpages.debian.org/unstable/keepalived/keepalived.conf.5.en.html for the advantages of using `track_process` instead of pgrep/pidof/killall and the likes.
and according to my open source slogan '_you need it, you implement it_' here is a PR introducing the configuration options for `track_process`
Greetings
Klaus
=> implemented track_process

templates/keepalived-checks.j2, templates/keepalived-virtual-server.j2
Hello @evrardjp, Jean-Philippe,
I have added 2 parameters to your module:
`vserver.quorum`: allows to define the quorum weight needed to operate properly. If this quorum is not met, the sorry_server will respond instead. This allows for split brain avoidance mechanisms with a witness tie-breaker for example.
`*_check.delay_loop`: this parameter defines the base frequency with which health checks are done. `delay_before_retry` is an override for this parameter only in the case of failures. By setting `delay_loop` to an integer, the healthcheck will be run every that-much seconds.
I hope you like it, find it up to your standards, and merge it.
=> Add useful parameters to vserver and checks
