- README.md
- defaults/main.yml
- tasks/main.yml
Setting keepalived_use_latest_stable to true will always install
latest keepalived.
> New feature: always install latest keepalived

- defaults/main.yml
Fixed problem {"failed": true, "msg": "ERROR! with_dict expects a dict"}
> Fixed problem with loop over hash

- tasks/main.yml
Only start keepalived  after it has been configured.
> Do not start keepalived on install

- tasks/keepalived_install_apt.yml
- tasks/main.yml
- vars/ubuntu-14.04.yml
This introduces conditional includes of the variables for the
role installation. Currently, distribution support isn't extended.
> Bootstrap multi host support

- tasks/main.yml
This adds a way to have other variable files to be included.
Signed-off-by: Jean-Philippe Evrard <jean-philippe@evrard.me>
> Update with_first_found to latest openstack-ansible standards

- tasks/main.yml
- templates/keepalived.conf.j2
Allows instance notification scripts to be defined.  Uses the same dict format as the sync group notification scripts.
> Support instance notification scripts.

- README.md
- templates/keepalived.conf.j2
- vars/keepalived_haproxy_backup_example.yml
- vars/keepalived_haproxy_master_example.yml
Hello @evrardjp,
here comes a small PR which adds keepalived's **track_interface** option to the role.
Best
Jard
> added optional track_interface option

- handlers/main.yml
- tasks/main.yml
- vars/ubuntu-14.04.yml
- vars/ubuntu-16.04.yml
This should be done by the package management system, but I forgot
to ensure to enforce it.
This commit should do the trick.
> Ensure keepalived is enabled on boot

- templates/keepalived.conf.j2
- vars/keepalived_haproxy_backup_example.yml
- vars/keepalived_haproxy_master_example.yml
Merge branch 'master' of https://github.com/BjoernT/ansible-keepalived
into BjoernT-master.
This is modified to solve merge conflicts and still keep the
features asked.
It generally is less intrusive for updates, as this won't change
the config file by default.
> Adding timeout attribute for check script

- tasks/keepalived_install_zypper.yml
- tasks/main.yml
- vars/suse.yml
This patch adds SUSE support for the keepalived role
> Add SUSE support

- tests/deploy.yml
- tests/functional-test.yml
- tests/keepalived_haproxy_combined_example.yml
Provide a better example that scales with a larger amount of
keepalived nodes.
> New sensible defaults

- templates/keepalived.conf.j2
Just found out that there was no `weight` option for the keepalived configuration file and added it. Cheers.
> Added weight to the template to make adjustment of priority possible

- templates/keepalived.conf.j2
Add the possibility to add virtual_rules in keepalived.conf
> Add virtual_rules to template

- tasks/main.yml
- templates/keepalived.conf.j2
add ipv6.ip_nonlocal_bind
add per group track_scripts
make script user configurable
> add ipv6.ip_nonlocal_bind, group track_scripts

- templates/keepalived.conf.j2
- tests/keepalived_haproxy_master_example.yml
Aloha,
added more variables for:
TCP_CHECK
SSL_GET
MISC_CHECK
added additional checks
HTTP_GET
DNS_CHECK
https://manpages.debian.org/stretch/keepalived/keepalived.conf.5.en.html
Regards.
> Extend and add Healthchecks

- Vagrantfile
- tasks/keepalived_selinux.yml
- tests/deploy.yml
my changes for #124 where incomplete
> Fix for #124

- defaults/main.yml
- tasks/main.yml
This solves https://github.com/evrardjp/ansible-keepalived/issues/131
> Added systemd option service restart=always

- handlers/main.yml
- tasks/main.yml
> only reload if config has changed

- .ansible-lint
- handlers/main.yml
- molecule/default/cleanup.yml
- molecule/default/converge.yml
- molecule/default/prepare.yml
- molecule/default/side_effect.yml
- molecule/default/verify.yml
- tasks/keepalived_selinux.yml
- tasks/keepalived_selinux_compile.yml
- tasks/main.yml
- templates/keepalived.conf.j2
- tests/keepalived_haproxy_backup_example.yml
- tests/keepalived_haproxy_combined_example.yml
- tests/keepalived_haproxy_master_example.yml
- tests/playbook-with-combined-vars.yml
- tests/playbook-with-fine-grained-vars.yml
As discussed in (draft) https://github.com/evrardjp/ansible-keepalived/pull/203.
Any further input is welcome.
> General ansible practices refresh

- meta/main.yml
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/masked-keepalived/converge.yml
CentOS 7 is outdated and sometimes fail due to flakey mirrors.
Need to update the OS list to something more recent.
> Update default scenario OSes

- meta/main.yml
This should get us to the top of the page 2.
Next step is to include this role in a collection to reach page 1.
> Add more meta tags to improve visibility on galaxy

- dev-requirements.txt
fixes https://github.com/evrardjp/ansible-keepalived/actions/runs/4936871377/jobs/8824937354
just a interim exit from the pip hell until some upstream fixes are available
> Fix test run for ansible latest
